// All user-facing Danish copy in one place (PROJECT.md convention).
export const da = {
	appName: 'Datoafstemning',
	createTitle: 'Opret afstemning',
	createIntro:
		'Vælg nogle datoer, tilføj de personer du vil spørge, og del deres personlige link. Hver deltager svarer, om de foretrækker, kan eller ikke kan.',
	fieldTitle: 'Titel',
	fieldDescription: 'Beskrivelse',
	datesSection: 'Mulige datoer',
	datesHint: 'Tilføj mindst én dato. Tidspunkter er valgfri.',
	addDate: '+ Tilføj dato',
	from: 'Fra',
	to: 'Til',
	participantsSection: 'Deltagere',
	participantsHint: 'Giv hver deltager et navn, og kopiér deres link til dem bagefter.',
	addParticipant: '+ Tilføj deltager',
	name: 'Navn',
	copyLink: 'Kopiér link',
	linkCopied: 'Linket er kopieret',
	create: 'Opret afstemning',
	created: 'Oprettet',
	remove: 'Fjern',
	errorNoTitle: 'Giv afstemningen en titel',
	errorNoDates: 'Tilføj mindst én dato',
	errorEndNeedsStart: 'Angiv et starttidspunkt før du sætter et sluttidspunkt',
	errorEndBeforeStart: 'Sluttidspunkt kan ikke ligge før starttidspunkt',

	// Response page (/r/[token])
	greeting: 'Hej',
	responseIntro: 'Vælg de datoer, der passer dig bedst',
	datesQuestion: 'Hvordan passer datoerne dig?',
	prefPreferred: 'Foretrukket',
	prefAvailable: 'Kan godt',
	prefUnavailable: 'Kan ikke',
	noteLabel: 'Bemærkning (valgfri)',
	notePlaceholder: 'Fx: Jeg kan ikke om morgenen',
	sendAnswer: 'Send svar',
	savedTitle: 'Tak! Dit svar er gemt.',
	savedSub: 'Du kan ændre dit svar, indtil afstemningen lukker.',
	editAnswer: 'Rediger',
	closedBanner: 'Afstemningen er lukket',
	linkNotFound: 'Linket findes ikke',
	linkNotFoundSub: 'Tjek at du har hele linket med, eller bed arrangøren sende det igen.',
	chooseEach: 'Vælg en mulighed for hver dato',

	// Organizer dashboard (/e/[token])
	dashboardTitle: 'Oversigt',
	organizerLinkTitle: 'Gem dette link',
	organizerLinkWarning:
		'Dette er din eneste vej tilbage til afstemningen og resultaterne. Gem det som bogmærke. Det kan ikke gendannes, hvis du mister det. Del det ikke med deltagerne.',
	resultsSection: 'Resultater',
	bestDate: 'Bedste dato',
	answered: 'Har svaret',
	pending: 'Mangler at svare',
	showWho: 'Vis hvem der har svaret',
	hideWho: 'Skjul',
	showNote: 'Vis bemærkning',
	hideNote: 'Skjul bemærkning',
	closePoll: 'Luk afstemning',
	reopenPoll: 'Åbn afstemning igen',
	statusOpen: 'Åben',
	statusClosed: 'Lukket',
	save: 'Gem',
	edit: 'Rediger',
	confirmDeleteOption: 'Denne dato har svar. Slet den alligevel?',
	confirmDeleteInvitee:
		'Denne deltager har svaret. Fjern dem alligevel? Deres link holder op med at virke.'
} as const;
