// GENERATED by scripts/gen-types.sh - do not edit.
//
// The types the Playwright specs import. Derived from messages/*.json (Locale)
// and the responses.preference CHECK constraint (Preference), so the test-side
// types cannot drift from what the Go app actually accepts.

export type Locale = 'da' | 'en' | 'fr';

export type Preference = 'preferred' | 'available' | 'unavailable';
