// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DateOption struct {
	ID        string
	EventID   string
	StartsAt  pgtype.Text
	EndsAt    pgtype.Text
	Label     pgtype.Text
	SortOrder int32
}

type Event struct {
	ID             string
	Title          string
	Description    pgtype.Text
	Locale         string
	PollMode       string
	OrganizerToken string
	ShareToken     pgtype.Text
	Status         string
	CreatedAt      string
}

type Invitee struct {
	ID        string
	EventID   string
	Label     string
	Token     string
	Note      pgtype.Text
	CreatedAt string
}

type Response struct {
	InviteeID    string
	DateOptionID string
	Preference   string
	UpdatedAt    string
}
