// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const answeredInviteeIDs = `-- name: AnsweredInviteeIDs :many
SELECT DISTINCT r.invitee_id AS id
FROM responses r JOIN invitees i ON i.id = r.invitee_id
WHERE i.event_id = $1
`

func (q *Queries) AnsweredInviteeIDs(ctx context.Context, eventID string) ([]string, error) {
	rows, err := q.db.Query(ctx, answeredInviteeIDs, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countInvitees = `-- name: CountInvitees :one
SELECT COUNT(*) AS n FROM invitees WHERE event_id = $1
`

func (q *Queries) CountInvitees(ctx context.Context, eventID string) (int64, error) {
	row := q.db.QueryRow(ctx, countInvitees, eventID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const dateOptionsForEvent = `-- name: DateOptionsForEvent :many
SELECT id, event_id, starts_at, ends_at, label, sort_order FROM date_options WHERE event_id = $1 ORDER BY sort_order
`

func (q *Queries) DateOptionsForEvent(ctx context.Context, eventID string) ([]DateOption, error) {
	rows, err := q.db.Query(ctx, dateOptionsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DateOption{}
	for rows.Next() {
		var i DateOption
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Label,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDateOption = `-- name: DeleteDateOption :exec
DELETE FROM date_options WHERE id = $1
`

func (q *Queries) DeleteDateOption(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDateOption, id)
	return err
}

const deleteInvitee = `-- name: DeleteInvitee :exec
DELETE FROM invitees WHERE id = $1
`

func (q *Queries) DeleteInvitee(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteInvitee, id)
	return err
}

const deleteResponsesForInvitee = `-- name: DeleteResponsesForInvitee :exec
DELETE FROM responses WHERE invitee_id = $1
`

func (q *Queries) DeleteResponsesForInvitee(ctx context.Context, inviteeID string) error {
	_, err := q.db.Exec(ctx, deleteResponsesForInvitee, inviteeID)
	return err
}

const deleteResponsesForOption = `-- name: DeleteResponsesForOption :exec
DELETE FROM responses WHERE date_option_id = $1
`

func (q *Queries) DeleteResponsesForOption(ctx context.Context, dateOptionID string) error {
	_, err := q.db.Exec(ctx, deleteResponsesForOption, dateOptionID)
	return err
}

const eventByID = `-- name: EventByID :one
SELECT id, title, description, locale, poll_mode, organizer_token, share_token, status, created_at FROM events WHERE id = $1
`

func (q *Queries) EventByID(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRow(ctx, eventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Locale,
		&i.PollMode,
		&i.OrganizerToken,
		&i.ShareToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const eventByOrganizerToken = `-- name: EventByOrganizerToken :one
SELECT id, title, description, locale, poll_mode, organizer_token, share_token, status, created_at FROM events WHERE organizer_token = $1
`

func (q *Queries) EventByOrganizerToken(ctx context.Context, organizerToken string) (Event, error) {
	row := q.db.QueryRow(ctx, eventByOrganizerToken, organizerToken)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Locale,
		&i.PollMode,
		&i.OrganizerToken,
		&i.ShareToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const eventByShareToken = `-- name: EventByShareToken :one
SELECT id, title, description, locale, poll_mode, organizer_token, share_token, status, created_at FROM events WHERE share_token = $1
`

func (q *Queries) EventByShareToken(ctx context.Context, shareToken pgtype.Text) (Event, error) {
	row := q.db.QueryRow(ctx, eventByShareToken, shareToken)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Locale,
		&i.PollMode,
		&i.OrganizerToken,
		&i.ShareToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const eventResponses = `-- name: EventResponses :many
SELECT r.invitee_id, r.date_option_id, r.preference, r.updated_at FROM responses r JOIN invitees i ON i.id = r.invitee_id
WHERE i.event_id = $1
`

func (q *Queries) EventResponses(ctx context.Context, eventID string) ([]Response, error) {
	rows, err := q.db.Query(ctx, eventResponses, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Response{}
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.InviteeID,
			&i.DateOptionID,
			&i.Preference,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDateOption = `-- name: InsertDateOption :exec
INSERT INTO date_options (id, event_id, starts_at, ends_at, sort_order)
VALUES ($1, $2, $3, $4, $5)
`

type InsertDateOptionParams struct {
	ID        string
	EventID   string
	StartsAt  pgtype.Text
	EndsAt    pgtype.Text
	SortOrder int32
}

func (q *Queries) InsertDateOption(ctx context.Context, arg InsertDateOptionParams) error {
	_, err := q.db.Exec(ctx, insertDateOption,
		arg.ID,
		arg.EventID,
		arg.StartsAt,
		arg.EndsAt,
		arg.SortOrder,
	)
	return err
}

const insertDateOptionAppend = `-- name: InsertDateOptionAppend :exec
INSERT INTO date_options (id, event_id, starts_at, ends_at, sort_order)
VALUES ($1, $2, $3, $4, $5)
`

type InsertDateOptionAppendParams struct {
	ID        string
	EventID   string
	StartsAt  pgtype.Text
	EndsAt    pgtype.Text
	SortOrder int32
}

func (q *Queries) InsertDateOptionAppend(ctx context.Context, arg InsertDateOptionAppendParams) error {
	_, err := q.db.Exec(ctx, insertDateOptionAppend,
		arg.ID,
		arg.EventID,
		arg.StartsAt,
		arg.EndsAt,
		arg.SortOrder,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec

INSERT INTO events (id, title, description, locale, poll_mode, organizer_token, share_token, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'open', $8)
`

type InsertEventParams struct {
	ID             string
	Title          string
	Description    pgtype.Text
	Locale         string
	PollMode       string
	OrganizerToken string
	ShareToken     pgtype.Text
	CreatedAt      string
}

// Ported 1:1 from src/lib/data/d1.ts. Every app SQL statement lives here, the
// single home for query-building (mirroring the original's discipline).
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Locale,
		arg.PollMode,
		arg.OrganizerToken,
		arg.ShareToken,
		arg.CreatedAt,
	)
	return err
}

const insertInvitee = `-- name: InsertInvitee :exec
INSERT INTO invitees (id, event_id, label, token, note, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertInviteeParams struct {
	ID        string
	EventID   string
	Label     string
	Token     string
	Note      pgtype.Text
	CreatedAt string
}

func (q *Queries) InsertInvitee(ctx context.Context, arg InsertInviteeParams) error {
	_, err := q.db.Exec(ctx, insertInvitee,
		arg.ID,
		arg.EventID,
		arg.Label,
		arg.Token,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const inviteeByToken = `-- name: InviteeByToken :one
SELECT id, event_id, label, token, note, created_at FROM invitees WHERE token = $1
`

func (q *Queries) InviteeByToken(ctx context.Context, token string) (Invitee, error) {
	row := q.db.QueryRow(ctx, inviteeByToken, token)
	var i Invitee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Label,
		&i.Token,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const inviteesForEvent = `-- name: InviteesForEvent :many
SELECT id, event_id, label, token, note, created_at FROM invitees WHERE event_id = $1 ORDER BY created_at
`

func (q *Queries) InviteesForEvent(ctx context.Context, eventID string) ([]Invitee, error) {
	rows, err := q.db.Query(ctx, inviteesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitee{}
	for rows.Next() {
		var i Invitee
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Label,
			&i.Token,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSortOrder = `-- name: MaxSortOrder :one
SELECT MAX(sort_order) AS m FROM date_options WHERE event_id = $1
`

func (q *Queries) MaxSortOrder(ctx context.Context, eventID string) (interface{}, error) {
	row := q.db.QueryRow(ctx, maxSortOrder, eventID)
	var m interface{}
	err := row.Scan(&m)
	return m, err
}

const renameInvitee = `-- name: RenameInvitee :exec
UPDATE invitees SET label = $2 WHERE id = $1
`

type RenameInviteeParams struct {
	ID    string
	Label string
}

func (q *Queries) RenameInvitee(ctx context.Context, arg RenameInviteeParams) error {
	_, err := q.db.Exec(ctx, renameInvitee, arg.ID, arg.Label)
	return err
}

const responsesForInvitee = `-- name: ResponsesForInvitee :many
SELECT invitee_id, date_option_id, preference, updated_at FROM responses WHERE invitee_id = $1
`

func (q *Queries) ResponsesForInvitee(ctx context.Context, inviteeID string) ([]Response, error) {
	rows, err := q.db.Query(ctx, responsesForInvitee, inviteeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Response{}
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.InviteeID,
			&i.DateOptionID,
			&i.Preference,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const results = `-- name: Results :many
SELECT d.id AS id,
	SUM(CASE WHEN r.preference = 'preferred'   THEN 1 ELSE 0 END)::bigint AS preferred,
	SUM(CASE WHEN r.preference = 'available'   THEN 1 ELSE 0 END)::bigint AS available,
	SUM(CASE WHEN r.preference = 'unavailable' THEN 1 ELSE 0 END)::bigint AS unavailable
FROM date_options d
LEFT JOIN responses r ON r.date_option_id = d.id
WHERE d.event_id = $1
GROUP BY d.id
ORDER BY d.sort_order
`

type ResultsRow struct {
	ID          string
	Preferred   int64
	Available   int64
	Unavailable int64
}

func (q *Queries) Results(ctx context.Context, eventID string) ([]ResultsRow, error) {
	rows, err := q.db.Query(ctx, results, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResultsRow{}
	for rows.Next() {
		var i ResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.Preferred,
			&i.Available,
			&i.Unavailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveNote = `-- name: SaveNote :exec
UPDATE invitees SET note = $2 WHERE id = $1
`

type SaveNoteParams struct {
	ID   string
	Note pgtype.Text
}

func (q *Queries) SaveNote(ctx context.Context, arg SaveNoteParams) error {
	_, err := q.db.Exec(ctx, saveNote, arg.ID, arg.Note)
	return err
}

const setEventLocale = `-- name: SetEventLocale :exec
UPDATE events SET locale = $2 WHERE id = $1
`

type SetEventLocaleParams struct {
	ID     string
	Locale string
}

func (q *Queries) SetEventLocale(ctx context.Context, arg SetEventLocaleParams) error {
	_, err := q.db.Exec(ctx, setEventLocale, arg.ID, arg.Locale)
	return err
}

const setEventStatus = `-- name: SetEventStatus :exec
UPDATE events SET status = $2 WHERE id = $1
`

type SetEventStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) SetEventStatus(ctx context.Context, arg SetEventStatusParams) error {
	_, err := q.db.Exec(ctx, setEventStatus, arg.ID, arg.Status)
	return err
}

const setPollMode = `-- name: SetPollMode :exec
UPDATE events SET poll_mode = $2 WHERE id = $1
`

type SetPollModeParams struct {
	ID       string
	PollMode string
}

func (q *Queries) SetPollMode(ctx context.Context, arg SetPollModeParams) error {
	_, err := q.db.Exec(ctx, setPollMode, arg.ID, arg.PollMode)
	return err
}

const updateDateOption = `-- name: UpdateDateOption :exec
UPDATE date_options SET starts_at = $2, ends_at = $3 WHERE id = $1
`

type UpdateDateOptionParams struct {
	ID       string
	StartsAt pgtype.Text
	EndsAt   pgtype.Text
}

func (q *Queries) UpdateDateOption(ctx context.Context, arg UpdateDateOptionParams) error {
	_, err := q.db.Exec(ctx, updateDateOption, arg.ID, arg.StartsAt, arg.EndsAt)
	return err
}

const updateEventDetails = `-- name: UpdateEventDetails :exec
UPDATE events SET title = $2, description = $3 WHERE id = $1
`

type UpdateEventDetailsParams struct {
	ID          string
	Title       string
	Description pgtype.Text
}

func (q *Queries) UpdateEventDetails(ctx context.Context, arg UpdateEventDetailsParams) error {
	_, err := q.db.Exec(ctx, updateEventDetails, arg.ID, arg.Title, arg.Description)
	return err
}

const upsertResponse = `-- name: UpsertResponse :exec
INSERT INTO responses (invitee_id, date_option_id, preference, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (invitee_id, date_option_id)
DO UPDATE SET preference = excluded.preference, updated_at = excluded.updated_at
`

type UpsertResponseParams struct {
	InviteeID    string
	DateOptionID string
	Preference   string
	UpdatedAt    string
}

func (q *Queries) UpsertResponse(ctx context.Context, arg UpsertResponseParams) error {
	_, err := q.db.Exec(ctx, upsertResponse,
		arg.InviteeID,
		arg.DateOptionID,
		arg.Preference,
		arg.UpdatedAt,
	)
	return err
}
