#!/usr/bin/env bash
# Generate src/lib/types.ts - the two types the Playwright specs import.
#
# They're derived from the same sources the Go code uses, so they can't drift:
#   Locale     <- the messages/*.json bundles that exist
#   Preference <- the CHECK constraint on responses.preference in the schema
#
# src/ holds nothing hand-written; it is entirely generated (see .gitattributes).
# The specs import '../src/lib/types', which is why the file lives there.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT=src/lib/types.ts
SCHEMA=internal/db/migrations/0001_init.sql

# messages/da.json -> 'da'
locales=$(find messages -name '*.json' -exec basename {} .json \; | sort | sed "s/^/'/;s/\$/'/" | paste -sd '|' - | sed 's/|/ | /g')

# ... CHECK (preference IN ('preferred', 'available', 'unavailable')) -> the list
prefs=$(grep -o "preference IN ([^)]*)" "$SCHEMA" \
	| sed "s/preference IN (//;s/)//" \
	| tr -d " '" | tr ',' '\n' | sed "s/^/'/;s/\$/'/" | paste -sd '|' - | sed 's/|/ | /g')

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
// GENERATED by scripts/gen-types.sh - do not edit.
//
// The types the Playwright specs import. Derived from messages/*.json (Locale)
// and the responses.preference CHECK constraint (Preference), so the test-side
// types cannot drift from what the Go app actually accepts.

export type Locale = $locales;

export type Preference = $prefs;
EOF

echo "wrote $OUT"
